### ISSUE TITLE
Code allows a starting point other than main() at runtime

### ISSUE THREAD

**Issue by robsimmons** [frankpfenning/C0#18]

**Comment by frankpfenning** [comment]
Resolved, but allowing -r "f(e1,...,en)" as command line arguments.

Also, while codex is running, r e will run the expression e (recursively),
stepping through it as usual.

There are some caveats: on the top level, the function call may not have
any spaces in it due to a shortcoming on the GetOpt SML/NJ library.

Codex no longer requires there to be a main function, but if there
isn't one, a starting point must be specified.
