### ISSUE TITLE
Error locations off by one in first line of file

### ISSUE THREAD

**Issue by frankpfenning** [frankpfenning/C0#42]
Somehow, error locations are off-by-one in the first line
of a file.  Error locations are correct when coin is parsing
interactively.

**Comment by robsimmons** [comment]
In coin/coin.sml, remember_pos is always initialized to 2, not 1. Similarly initializing the stream at 2 instead of 1 in makeLexer seems to resolve this issue. That's not particularly pleasing, as resolutions go, but that's the way I resolved this in r234. I'll let Frank decide whether that's good enough to close the issue.

**Comment by frankpfenning** [comment]
It works, "just because".  I am sure at some point this will come back to us, for now
I will mark it as closed.
